### ISSUE TITLE
v1.0.1 gemspec requires redis 2.x?

### ISSUE THREAD

**Issue by ashanbrown** [whazzmaster/guard-redis#6]
I wanted the v1.0.1 update to get rid of the guard deprecation warnings, but it locks the redis version at 2.x.  Do you know of any issues with this gem and redis 3.x?  I was using an earlier version of this gem just fine with redix 3.x? Thanks (and thanks for publishing this gem).

**Comment by whazzmaster** [comment]
I don't know of any reason to keep it bound. I'll look at removing that version lock- thanks for letting me know; it's been awhile since I've needed this for a project so hadn't run into this.

**Comment by chifung7** [comment]
I also run into this problem.  Please fix it.

**Comment by whazzmaster** [comment]
The 2.0.0 gem release fixes this issue. There's a major version bump due to a potentially non-backwards compatible change, but unless you were specifying a pidfile location that wasn't writeable it shouldn't be an issue.
